import ClientProviders from "@/components/ClientProviders";
import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Poppins } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./helper/ReactQueryProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <ReactQueryProvider>
        <ClientProviders>
          <div className="h-screen flex flex-col overflow-hidden" >
            <Header />
            <div className="flex flex-1 overflow-hidden">
              <Sidebar />
              <main className="w-full max-h-screen overflow-hidden">
                {children}
              </main>
            </div>
          </div>
        </ClientProviders>
        </ReactQueryProvider>
      </body>
    </html>
  );
}

export default RootLayout;
