import ClientProviders from "@/components/ClientProviders";
import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Poppins } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./helper/ReactQueryProvider";
import { AuthProvider } from "@/app/context/AuthContext";
import { GoogleOAuthProvider } from "@react-oauth/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}>
          <ReactQueryProvider>
            <AuthProvider>
              <ClientProviders>
                {children}
              </ClientProviders>
            </AuthProvider>
          </ReactQueryProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}

export default RootLayout;
